import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // So first off the states will have to hold the character's name, what they're doing, and where they're doing it at the very least.
  const [character, setCharacter] = useState('')
  const [verb, setVerb] = useState('')
  const [location, setLocation] = useState('')
  const [prompt, setPrompt] = useState('')
  const [oneRandomWord, setOneRandomWord] = useState('')

  // API calls to the random word and dictionary APIs will happen only after a button press, so no need for a useEffect yet

  const handleOneWordPrompt = async () => {
    // For those who just want one random word to build a prompt around
    const randomWord = await axios.get('https://random-word-api.vercel.app/api?words=1')
    console.log(randomWord.data[0])
    setOneRandomWord(randomWord.data[0])
  }

  const handlePrompt = async () => {
    // This will fire off the API calls, first to the random word API(for one noun and one verb) then the dictionary API. The dictionary API will help with the proper usage of the word.
    const randomWord = await axios.get('https://random-word-api.vercel.app/api?words=1')
    console.log(randomWord.data[0])
    const definition = await axios.get(`https://api.dictionaryapi.dev/api/v2/entries/en/${randomWord.data[0]}`)
    console.log(definition)
  }

  return (
    <>
      <Head>
        <title>Character Prompts Randomizer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h2>Prompts go here</h2>
        {oneRandomWord}
        <button onClick={() => handleOneWordPrompt()}>Single Word Prompt</button>
        <button onClick={() => handlePrompt()}>Generate Prompt</button>
      </main>
    </>
  )
}
